"""Add field name

Revision ID: 33275aaf44d7
Revises: 8745fb6a18f0
Create Date: 2024-07-18 13:51:24.500404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33275aaf44d7'
down_revision = '8745fb6a18f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('meme_text', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_meme_meme_text'), 'meme', ['meme_text'], unique=False)
    op.drop_index('ix_memes_meme_text', table_name='memes')
    op.drop_table('memes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meme_text', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='memes_pkey')
    )
    op.create_index('ix_memes_meme_text', 'memes', ['meme_text'], unique=False)
    op.drop_index(op.f('ix_meme_meme_text'), table_name='meme')
    op.drop_table('meme')
    # ### end Alembic commands ###
