"""First migration

Revision ID: 8745fb6a18f0
Revises: 
Create Date: 2024-07-11 23:54:20.566250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8745fb6a18f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meme_text', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memes_meme_text'), 'memes', ['meme_text'], unique=False)
    op.drop_table('pgtest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pgtest',
    sa.Column('testval', sa.VARCHAR(length=10), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_memes_meme_text'), table_name='memes')
    op.drop_table('memes')
    # ### end Alembic commands ###
